// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SBRPLogPsi.Models;

#nullable disable

namespace SBRPLogPsi.Migrations
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20250217104400_InboundStockOrderLog")]
    partial class InboundStockOrderLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("psi")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SBRPLogPsi.Models.InboundStockOrderDetailLog", b =>
                {
                    b.Property<int>("LogNo")
                        .HasColumnType("int");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<short>("ItemNo")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ArchivedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<byte>("LogTypeNo")
                        .HasColumnType("tinyint");

                    b.Property<int>("LoginActionNo")
                        .HasColumnType("int");

                    b.Property<int>("ProductNo")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LogNo", "OrderNo", "ItemNo");

                    b.HasIndex("ProductNo");

                    b.ToTable("InboundStockOrderDetailLog", "psi");
                });

            modelBuilder.Entity("SBRPLogPsi.Models.InboundStockOrderLog", b =>
                {
                    b.Property<int>("LogNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogNo"));

                    b.Property<DateTime>("ArchivedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("CreatedPerson")
                        .HasColumnType("smallint");

                    b.Property<short>("DaySerialNo")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<short?>("DeletedPerson")
                        .HasColumnType("smallint");

                    b.Property<byte>("DetailPriceItemNo")
                        .HasColumnType("tinyint");

                    b.Property<short>("DetailRowCount")
                        .HasColumnType("smallint");

                    b.Property<decimal>("DetailSubAmount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<int>("DetailSubQty")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte>("LogTypeNo")
                        .HasColumnType("tinyint");

                    b.Property<int>("LoginActionNo")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OrderDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("date");

                    b.Property<short>("OrderDateNo")
                        .HasColumnType("smallint");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("CHAR(12)");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<byte>("SIGNo")
                        .HasColumnType("tinyint");

                    b.Property<short?>("StockNo")
                        .HasColumnType("smallint");

                    b.Property<short>("SupplierNo")
                        .HasColumnType("smallint");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<short?>("UpdatedPerson")
                        .HasColumnType("smallint");

                    b.HasKey("LogNo");

                    b.HasIndex("SupplierNo");

                    b.ToTable("InboundStockOrderLog", "psi");
                });
#pragma warning restore 612, 618
        }
    }
}
