CREATE TABLE [common].[Company] (
    [CompanyNo] smallint NOT NULL DEFAULT (NEXT VALUE FOR common.seqCompany),
    [SIGNo] tinyint NOT NULL DEFAULT (0),
    [CompanyId] CHAR(16) NOT NULL,
    [TaxId] CHAR(10) NOT NULL,
    [CompanyName] nvarchar(40) NOT NULL,
    [CompanyNameAbbr] nvarchar(12) NOT NULL,
    [CompanyDirector] nvarchar(16) NULL,
    [CompanyAddress] nvarchar(64) NULL,
    [PostalAddress] nvarchar(64) NULL,
    [CompanyPhone] VARCHAR(16) NULL,
    [CompanyWeb] VARCHAR(64) NULL,
    [IsSystemPredefined] bit NOT NULL DEFAULT (0),
    [IsDisabled] bit NOT NULL DEFAULT (0),
    [Remark] nvarchar(48) NULL,
    [IsDeleted] bit NOT NULL DEFAULT (0),
    [CreatedPerson] smallint NOT NULL,
    [CreatedDate] datetime2 NOT NULL DEFAULT (GETDATE()),
    [UpdatedPerson] smallint NULL,
    [UpdatedDate] datetime2 NULL,
    [DeletedPerson] smallint NULL,
    [DeletedDate] datetime2 NULL,
    [IsSubmitted] bit NULL,
    [SubmittedPerson] smallint NULL,
    [SubmittedDate] datetime2 NULL,
    [IsApproved] bit NULL,
    [ApprovedPerson] smallint NULL,
    [ApprovedDate] datetime2 NULL,
    CONSTRAINT [PK_Company] PRIMARY KEY ([CompanyNo])
);
GO
CREATE INDEX [IX_Company_CompanyId] ON [common].[Company] ([CompanyId]);