CREATE TABLE [common].[User] (
    [UserNo] smallint NOT NULL DEFAULT (NEXT VALUE FOR common.seqUser),
    [SIGNo] tinyint NOT NULL DEFAULT (0),
    [UserId] CHAR(16) NULL,
    [EmployeeNo] smallint NULL,
    [PersonNo] int NOT NULL,
    [UserGroupNo] smallint NOT NULL,
    [UserRoleNo] smallint NOT NULL,
    [LoginId] CHAR(32) NOT NULL,
    [PasswordHash] VARCHAR(128) NOT NULL,
    [Email] nvarchar(max) NOT NULL,
    [IsReadonly] bit NOT NULL DEFAULT (0),
    [IsDisabled] bit NOT NULL DEFAULT (0),
    [IsSystemPredefined] bit NOT NULL DEFAULT (0),
    [IsLoggedOn] bit NULL,
    [HasBeenLocked] bit NOT NULL DEFAULT (0),
    [IsDeleted] bit NOT NULL DEFAULT (0),
    [ExpirationDate] date NULL,
    [CreatedPerson] smallint NOT NULL,
    [CreatedDate] datetime2 NOT NULL DEFAULT (GETDATE()),
    [UpdatedPerson] smallint NULL,
    [UpdatedDate] datetime2 NULL,
    [DeletedPerson] smallint NULL,
    [DeletedDate] datetime2 NULL,
    [IsSubmitted] bit NULL,
    [SubmittedPerson] smallint NULL,
    [SubmittedDate] datetime2 NULL,
    [IsApproved] bit NULL,
    [ApprovedPerson] smallint NULL,
    [ApprovedDate] datetime2 NULL,
    [LastLoggedOnDate] datetime2 NULL,
    [LastLoggedOutDate] datetime2 NULL,
    [LockedDate] datetime2 NULL,
    [LastPasswordFailedDate] datetime2 NULL,
    [PasswordFailureAttemptCount] smallint NULL,
    CONSTRAINT [PK_User] PRIMARY KEY ([UserNo]),
    CONSTRAINT [FK_User_Person_PersonNo] FOREIGN KEY ([PersonNo]) REFERENCES [common].[Person] ([PersonNo]) ON DELETE CASCADE
);
GO
CREATE INDEX [IX_User_LoginId] ON [common].[User] ([LoginId]);
GO
CREATE INDEX [IX_User_PersonNo] ON [common].[User] ([PersonNo]);